### ISSUE TITLE
Error 999 on Slideshare URL

### ISSUE THREAD

**Issue by kfei** [itteco/iframely#109]
To reproduce, try `http://www.slideshare.net/NeilGreen1/type-script-vs-coffeescript-vs-es6` on 49d64e7
```
# curl http://localhost:8061/oembed?url=http://www.slideshare.net/NeilGreen1/type-script-vs-coffeescript-vs-es6
Using cache engine: node-cache
No local whitelist file detected...
Loading whitelist from http://iframely.com/qa/whitelist.json
Iframely plugins loaded:
   - custom domains: 189
   - generic & meta: 72

Starting Iframely...
Base URL for embeds that require hosted renders: https://<my_domain>.io

Iframely listening on port 8061
 - support@iframely.com - if you need help
 - twitter.com/iframely - news & updates
 - github.com/itteco/iframely - star & contribute
-- [16-03-12 10:14:06] Loading /iframely for http://www.slideshare.net/NeilGreen1/type-script-vs-coffeescript-vs-es6
-- [16-03-12 10:14:06]    -- response (by "htmlparser") 999
Error: Requested page error: 999
    at /iframely/modules/api/views.js:87:29
    at /iframely/node_modules/async/lib/async.js:52:16
    at /iframely/node_modules/async/lib/async.js:1166:30
    at asyncMethodCb (/iframely/lib/core.js:1298:28)
    at /iframely/lib/core.js:269:29
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
-- [16-03-12 10:14:06]    -- response (by "htmlparser") 999
Whitelist activated. Domains, including blacklisted: 1980
```

Thank you guys for the great efforts on this awesome project! :smile:

**Comment by kfei** [comment]
Sorry I'm going to close this issue since I'm not exactly know how to reproduce this. I went to this error in a Docker environment. After that I tried to reproduce it on my local machine (Mac, Linux and Docker) and things just became good. Weird. So it seems not an issue of iframely. Will post back once I got any new clue.

My Dockerfile FYI:

```Dockerfile
FROM node:5.8

EXPOSE 8061

ADD . /iframely

WORKDIR /iframely

RUN apt-get update && \
        apt-get install libkrb5-dev && \
        apt-get clean

RUN npm config set color false
RUN npm config set loglevel warn
RUN npm config set progress false

RUN npm install

CMD ["node", "server"]
```

**Comment by iparamonau** [comment]
The error 999 comes from SlideShare in that case and is similar to issue #108. 

I sense they have a common firewall provider, perhaps Cloudflare. If your servers get blocked there's an [upcoming option](https://github.com/itteco/iframely/commit/b0fc497249d45f51a9369b1d42979ff5f44f9e94) to route specific URLs through a different proxies.
