### ISSUE TITLE
Unexpected strict mode reserved word resulting in pm2 erroring

### ISSUE THREAD

**Issue by sudheesh001** [itteco/iframely#122]
Hey, We are using iframely to build `loklak/loklak_webclient` at loklak.net but we've been facing the issue to start the iframely services using pm2. The log shows the following error
```
loklak_webclient/iframely$ pm2 logs 2
[PM2] Tailing last 20 lines for [2] process 

iframely-app-2 (err):     at Function.Module._load (module.js:310:12)
iframely-app-2 (err):     at Module.require (module.js:365:17)
iframely-app-2 (err):     at require (module.js:384:17)
iframely-app-2 (err):     at Object.<anonymous> (/home/loklaktest/loklak_webclient/iframely/server.js:2:16)
iframely-app-2 (err):     at Module._compile (module.js:460:26)
iframely-app-2 (err):     at Object.Module._extensions..js (module.js:478:10)
iframely-app-2 (err): /home/loklaktest/loklak_webclient/iframely/utils.js:52
iframely-app-2 (err):         return function static(req, res, next) {
iframely-app-2 (err):                         ^^^^^^
iframely-app-2 (err): SyntaxError: Unexpected strict mode reserved word
iframely-app-2 (err):     at exports.runInThisContext (vm.js:73:16)
iframely-app-2 (err):     at Module._compile (module.js:443:25)
iframely-app-2 (err):     at Object.Module._extensions..js (module.js:478:10)
iframely-app-2 (err):     at Module.load (module.js:355:32)
iframely-app-2 (err):     at Function.Module._load (module.js:310:12)
iframely-app-2 (err):     at Module.require (module.js:365:17)
iframely-app-2 (err):     at require (module.js:384:17)
iframely-app-2 (err):     at Object.<anonymous> (/home/loklaktest/loklak_webclient/iframely/server.js:2:16)
iframely-app-2 (err):     at Module._compile (module.js:460:26)
iframely-app-2 (err):     at Object.Module._extensions..js (module.js:478:10)

[PM2] Streaming realtime logs for [2] process 

```

**Comment by iparamonau** [comment]
Our pm2 works fine and there were no changes to /iframely/utils.js with the regard to this function recently. Try launching Iframely without PM2, if all is fine - then something changed in your pm2 lately. If there are errors, try npm update - one library dependency was updated in the latest version
