### ISSUE TITLE
Inconsistencies running Docker image

### ISSUE THREAD

**Issue by jmunson** [itteco/iframely#188]
```shell
$ docker rm iframely2;docker run -it -p 8061:8061 -v $PWD/config.local.js:/iframely/config.local.js --name iframely2 iframely:latest
iframely2
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: cluster.js
error:   Cannot find forever process: 0
```

This does not happen every time, and re-running that will eventually work without changing anything.

Additionally, sometimes I get this while launching with docker-compose:
```shell

iframely_1    | data:    cluster.js:28 - Starting Iframely...                                                                                                                                                                                 
iframely_1    | data:    cluster.js:28 - Base URL for embeds that require hosted renders: http://localhost:8061/                                                                                                                              
iframely_1    | data:    cluster.js:28 -  - support@iframely.com - if you need help                                                                                                                                                           
iframely_1    | data:    cluster.js:28 -  - twitter.com/iframely - news & updates                                                                                                                                                             
iframely_1    | data:    cluster.js:28 -  - github.com/itteco/iframely - star & contribute                                                                                                                                                    
iframely_1    | data:    cluster.js:28 - iframely is running on 0.0.0.0:8061                                                                                                                                                                  
iframely_1    | data:    cluster.js:28 - API endpoints: /oembed and /iframely; Debugger UI: /debug                                                                                                                                            
iframely_1    | data:    cluster.js:28 - Iframely plugins loaded:                                                                                                                                                                             
iframely_1    | data:    cluster.js:28 -    - custom domains: 189                                                                                                                                                                             
iframely_1    | data:    cluster.js:28 -    - generic & meta: 98                                                                                                                                                                              
iframely_1    | data:    cluster.js:28 - Starting Iframely...                                                                                                                                                                                 
iframely_1    | data:    cluster.js:28 - Base URL for embeds that require hosted renders: http://localhost:8061/       
iframely_1    | data:    cluster.js:28 -  - support@iframely.com - if you need help                                    
iframely_1    | data:    cluster.js:28 -  - twitter.com/iframely - news & updates                                      
iframely_1    | data:    cluster.js:28 -  - github.com/itteco/iframely - star & contribute                             
iframely_1    | data:    cluster.js:28 - iframely is running on 0.0.0.0:8061                                           
iframely_1    | data:    cluster.js:28 - API endpoints: /oembed and /iframely; Debugger UI: /debug                     
iframely_1    | data:    cluster.js:28 - TypeError: parser.free is not a function                                      
iframely_1    | data:    cluster.js:28 -     at freeParser (_http_common.js:219:14)                                    
iframely_1    | data:    cluster.js:28 -     at TLSSocket.socketOnData (_http_client.js:483:5)                         
iframely_1    | data:    cluster.js:28 -     at TLSSocket.emit (events.js:160:13)                                      
iframely_1    | data:    cluster.js:28 -     at addChunk (_stream_readable.js:269:12)                                  
iframely_1    | data:    cluster.js:28 -     at readableAddChunk (_stream_readable.js:256:11)                          
iframely_1    | data:    cluster.js:28 -     at TLSSocket.Readable.push (_stream_readable.js:213:10)                   
iframely_1    | data:    cluster.js:28 -     at TLSWrap.onread (net.js:599:20)                                         
iframely_1    | data:    cluster.js:28 - -- [18-01-17 20:19:49] Whitelist activated. Domains, including blacklisted: 2036                                                                                                                     
iframely_1    | data:    cluster.js:28 - TypeError: parser.free is not a function                                      
iframely_1    | data:    cluster.js:28 -     at freeParser (_http_common.js:219:14)                                    
iframely_1    | data:    cluster.js:28 -     at TLSSocket.socketOnData (_http_client.js:483:5)                         
iframely_1    | data:    cluster.js:28 -     at TLSSocket.emit (events.js:160:13)                                      
iframely_1    | data:    cluster.js:28 -     at addChunk (_stream_readable.js:269:12)                                  
iframely_1    | data:    cluster.js:28 -     at readableAddChunk (_stream_readable.js:256:11)                          
iframely_1    | data:    cluster.js:28 -     at TLSSocket.Readable.push (_stream_readable.js:213:10)                   
iframely_1    | data:    cluster.js:28 -     at TLSWrap.onread (net.js:599:20)                                         
iframely_1    | data:    cluster.js:28 - -- [18-01-17 20:19:50] Whitelist activated. Domains, including blacklisted: 2036                   
```

It too is inconsistent, but has happened multiple times without changing anything or ever attempting to interface with iframely at all.

Any ideas on where I could look to better diagnose this?

**Comment by iparamonau** [comment]
Can't really help much with Docker as it was contributed to the project. But it like you might be having issues with Node version or TLS/OpenSSL version or simply there's a problematic SSL settings in your Iframely local config file that won't let the server start.

**Comment by jmunson** [comment]
Looks like the node version specified in the Dockerfile is 5.8, are the docs at https://iframely.com/docs/host still current where it says 

>Node.js version 0.10.22 and higher is required (was tested up to 0.12).

?  That could partially explain things.

To make things more confusing, when it does launch but shows the parser.free errors,  iframely still seems to function fine. I haven't put it to much use yet so I can't say what the side effects are, judging by the function name I suspect it might be leaking memory, but I haven't spent too much time with it yet so I can't say for sure.

**Comment by iparamonau** [comment]
Closing the issue for now. Docs have been updated, and there was a Docker-related PR in v 1.4.0. We can't do much more, but PRs are welcome.

**Comment by dessalines** [comment]
I'm running into this a frequent amount, and have no idea how to fix it.
