### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Yahav** [itteco/iframely#224]
Trying to get /render for https://www.youtube.com/watch?v=OWx2HROnTQ4
getting the following stacktrace:

```
2|iframely  | -- [19-10-19 19:58:51] 127.0.0.1 - Loading /render for https://www.youtube.com/watch?v=OWx2HROnTQ4
2|iframely  | -- [19-10-19 19:58:51]    -- fallback from domain to generic { 'youtube.com': true }
2|iframely  | -- [19-10-19 19:58:51]    -- Using cached meta for: https://www.youtube.com/watch?v=OWx2HROnTQ4
2|iframely  | -- [19-10-19 19:58:51]    -- Using cached oembed for: https://www.youtube.com/oembed?format=json&url=https://www.youtube.com/watch?v=OWx2HROnTQ4
2|iframely  | TypeError: Cannot read property 'replace' of undefined
2|iframely  |     at Object.exports.escapeValue (/home/yahav/iframely/node_modules/memcached/lib/utils.js:152:16)
2|iframely  |     at Client.setters (/home/yahav/iframely/node_modules/memcached/lib/memcached.js:929:19)
2|iframely  |     at Client.bowlofcurry [as set] (/home/yahav/iframely/node_modules/memcached/lib/utils.js:126:15)
2|iframely  |     at Object.engine.set (/home/yahav/iframely/lib/cache-engines/memcached.js:64:19)
2|iframely  |     at cache.set (/home/yahav/iframely/lib/cache.js:28:34)
2|iframely  |     at /home/yahav/iframely/lib/cache.js:94:21
2|iframely  |     at /home/yahav/iframely/modules/api/views.js:349:25
2|iframely  |     at finish (/home/yahav/iframely/lib/core.js:1471:21)
2|iframely  |     at asyncMethodCb (/home/yahav/iframely/lib/core.js:1590:25)
2|iframely  |     at /home/yahav/iframely/lib/core.js:704:29
2|iframely  | TypeError: Cannot read property 'replace' of undefined
2|iframely  |     at Object.exports.escapeValue (/home/yahav/iframely/node_modules/memcached/lib/utils.js:152:16)
2|iframely  |     at Client.setters (/home/yahav/iframely/node_modules/memcached/lib/memcached.js:929:19)
2|iframely  |     at Client.bowlofcurry [as set] (/home/yahav/iframely/node_modules/memcached/lib/utils.js:126:15)
2|iframely  |     at Object.engine.set (/home/yahav/iframely/lib/cache-engines/memcached.js:64:19)
2|iframely  |     at cache.set (/home/yahav/iframely/lib/cache.js:28:34)
2|iframely  |     at /home/yahav/iframely/lib/cache.js:94:21
2|iframely  |     at /home/yahav/iframely/modules/api/views.js:349:25
2|iframely  |     at finish (/home/yahav/iframely/lib/core.js:1471:21)
2|iframely  |     at asyncMethodCb (/home/yahav/iframely/lib/core.js:1590:25)
2|iframely  |     at /home/yahav/iframely/lib/core.js:704:29
```

Any idea?

**Comment by Yahav** [comment]
When i disable cache i get the following error for the same request:
```
1|iframely  | -- [19-10-19 20:17:02] 127.0.0.1 - Loading /render for https://www.youtube.com/watch?v=OWx2HROnTQ4
1|iframely  | -- [19-10-19 20:17:02]    -- fallback from domain to generic { 'youtube.com': true }
1|iframely  | NotFound: No render available
1|iframely  |     at /home/yahav/iframely/modules/api/views.js:361:29
1|iframely  |     at /home/yahav/iframely/node_modules/async/dist/async.js:421:16
1|iframely  |     at next (/home/yahav/iframely/node_modules/async/dist/async.js:5278:29)
1|iframely  |     at /home/yahav/iframely/node_modules/async/dist/async.js:906:16
1|iframely  |     at /home/yahav/iframely/lib/cache.js:101:21
1|iframely  |     at /home/yahav/iframely/modules/api/views.js:349:25
1|iframely  |     at finish (/home/yahav/iframely/lib/core.js:1471:21)
1|iframely  |     at asyncMethodCb (/home/yahav/iframely/lib/core.js:1590:25)
1|iframely  |     at /home/yahav/iframely/lib/core.js:704:29
1|iframely  |     at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by iparamonau** [comment]
Sorry we missed that issue. 

The `/render` endpoint that comes with the self-hosted version is only meant to help with providers that publish not JS-friendly HTML codes instead of iFrame (think - Facebook). 

Renders are not available for YouTube because the provider is publishing iFrame. 

Also, you can skip Iframely renders altogether with `SKIP_IFRAMELY_RENDERS: true` in your config (which is the default config I believe).
