### ISSUE TITLE
Unmatched closing comment causes SyntaxError when try to run, `node server`

### ISSUE THREAD

**Issue by luceat-lux-vestra** [itteco/iframely#331]
/home/ubuntu/iframely/config.local.js:256
            */
             ^
SyntaxError: Unexpected token /
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/ubuntu/iframely/config.js:395:21

**Comment by iparamonau** [comment]
Thanks!
