### ISSUE TITLE
Error in node v0.12.0 (TypeError: Cannot assign to read only property 'string' of (begin))

### ISSUE THREAD

**Issue by kulakowka** [itteco/iframely#48]
I have a problem.

The current node version on my computer is: `v0.12.0`

When I run the command `node server` the console displays:

```
Using cache engine: node-cache
No local whitelist file detected...
Loading whitelist from http://iframely.com/qa/whitelist.json
evalmachine.<anonymous>:2557
        s.string = s;
                 ^
TypeError: Cannot assign to read only property 'string' of (begin)
    at ultimate (evalmachine.<anonymous>:2557:18)
    at evalmachine.<anonymous>:3167:5
    at evalmachine.<anonymous>:6399:2
    at Object.exports.runInContext (vm.js:64:17)
    at Object.<anonymous> (/Users/kulakowka/Documents/node.js/iframely_for_geekhub/node_modules/jslint/lib/nodelint.js:9:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

When I run the command `npm test` the console displays: 

```
> iframely@0.7.2 test /Users/kulakowka/Documents/node.js/iframely_for_geekhub
> vows test/main.js --isolate --spec

evalmachine.<anonymous>:2557
        s.string = s;
                 ^
TypeError: Cannot assign to read only property 'string' of (begin)
    at ultimate (evalmachine.<anonymous>:2557:18)
    at evalmachine.<anonymous>:3167:5
    at evalmachine.<anonymous>:6399:2
    at Object.exports.runInContext (vm.js:64:17)
    at Object.<anonymous> (/Users/kulakowka/Documents/node.js/iframely_for_geekhub/node_modules/jslint/lib/nodelint.js:9:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
util.print: Use console.log instead

✗ Errored » 1 errored (0.000s)

npm ERR! Test failed.  See above for more details.
```

When I switched to node version v0.10.36, and then run command `node server`, Iframely worked.

I think the fault node version?

How to make iframely work with the latest version of the node?

**Comment by OKNoah** [comment]
Thanks, you inadvertently gave me the answer to my problem.

Node is in heavy development and you should expect things to break in new versions.

**Comment by nleush** [comment]
Current problem is in old jslint parser. But new version has new api, need some code update.

**Comment by iparamonau** [comment]
This should now be fixed in `develop` branch. You need to `npm update` since fix required update of couple dependencies.

Also, because of the change, 0.10.22 will become min supported version of Node.js.

**Comment by iparamonau** [comment]
Iframely version 0.8.0 is now released and is available in master branch
