### ISSUE TITLE
Self-hosting iframely - 

### ISSUE THREAD

**Issue by LiFaytheGoblin** [itteco/iframely#557]
Hello, I am self-hosting iframely (pulled the recent version), (on node v20.9.0, with pm2). The pm2 logs show an issue, and the service is not running on my server (Bad Gateway error). I am super confused - do I need to use an older node version?

```
2|iframely | ReferenceError: module is not defined in ES module scope
2|iframely | This file is being treated as an ES module because it has a '.js' file extension and '/home/web/iframely/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
2|iframely |     at file:///home/web/iframely/config.local.js:306:5
2|iframely |     at file:///home/web/iframely/config.local.js:307:3
2|iframely |     at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
2|iframely |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
2|iframely |     at async file:///home/web/iframely/config.js:392:17
```

Thanks!

**Comment by LiFaytheGoblin** [comment]
It looks like the server has an old config.local.js that still uses the old syntax. Just need to migrate :)
